def select_model(df_output, model_name):
    """
    Selects and returns the scores of a specified model from a DataFrame of model scores.

    This function searches a DataFrame, typically generated by the show_all() function,
    for a model matching the name being provided. If found, it returns the corresponding row 
    of scores. Otherwise, it issues a "Model Not Found""Model Not Found" message.

    Parameters
    ----------
    df_output : DataFrame
        A DataFrame containing scores of various models, usually outputted by show_all().
    model_name : str
        The name of the model to search for in the DataFrame.

    Returns
    -------
    Series or str
        The row from the DataFrame corresponding to the specified model.
        Otherwise, returns a "Model Not Found" message.
    """
